/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./Male/male_body_2.glb -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Beard: THREE.Mesh
    Hair_1: THREE.Mesh
    Hair_2: THREE.Mesh
    Visor_1: THREE.Mesh
    Visor_2: THREE.Mesh
    Visor_3: THREE.Mesh
    Body_2: THREE.Mesh
  }
  materials: {
    Accesories_Mat: THREE.MeshStandardMaterial
    MainBody_Mat: THREE.MeshStandardMaterial
  }
  animations: object[]
}

export function MaleBody2(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Male/Male_Body_2.glb') as GLTFResult

  materials.Accesories_Mat.roughness = 0;
  materials.Accesories_Mat.metalness = 0;


  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Body_2.geometry} material={materials.MainBody_Mat} />
      <mesh geometry={nodes.Beard.geometry} material={materials.Accesories_Mat} />
      <mesh geometry={nodes.Hair_1.geometry} material={materials.Accesories_Mat} />
      <mesh geometry={nodes.Hair_2.geometry} material={materials.Accesories_Mat} />
      <mesh geometry={nodes.Visor_1.geometry} material={materials.Accesories_Mat} />
      <mesh geometry={nodes.Visor_2.geometry} material={materials.Accesories_Mat} />
      <mesh geometry={nodes.Visor_3.geometry} material={materials.Accesories_Mat} />
    </group>
  )
}

useGLTF.preload('/models/Male/Male_Body_2.glb')
