/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { Outlines, useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useRef } from "react";
import { JSX } from "react/jsx-runtime";
import { RigidBody } from "@react-three/rapier";

type GLTFResult = GLTF & {
  nodes: {
    Ball: THREE.Mesh;
  };
  materials: {};
};

export function Ball(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF(
    "/models/in-game/Ball/Ball.glb",
  ) as unknown as GLTFResult;

  const meshRef = useRef<THREE.Mesh>(null);

  // useFrame((state, delta) => {
  //   if (meshRef.current) {
  //     meshRef.current.rotation.y += delta * 2;
  //     meshRef.current.rotation.x += delta * 1.5;

  //     // Sine wave movement for bobbing effect
  //     // state.clock.elapsedTime gives continuously increasing time
  //     // Math.sin creates value between -1 and 1
  //     // Multiply by amplitude (e.g., 2) and add frequency (e.g., * 2)
  //     meshRef.current.position.z = Math.sin(state.clock.elapsedTime * 2) * 5;
  //   }
  // });

  return (
    <group {...props} dispose={null}>
      <RigidBody colliders="ball" restitution={1.5} name="ball" type="dynamic">
        <mesh
          ref={meshRef}
          castShadow
          receiveShadow
          geometry={nodes.Ball.geometry}
          material={nodes.Ball.material}
        >
          <Outlines thickness={0.5} color="black" angle={0} />
        </mesh>
      </RigidBody>
    </group>
  );
}

useGLTF.preload("/models/in-game/Ball/Ball.glb");
