/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { JSX } from "react";

type GLTFResult = GLTF & {
  nodes: {
    Stadiump1: THREE.Mesh;
    Stadiump2: THREE.Mesh;
    Barriers: THREE.Mesh;
    GoalNet: THREE.Mesh;
    PitchBanner: THREE.Mesh;
    Grass_mesh: THREE.Mesh;
    Pitch_mesh: THREE.Mesh;
  };
  materials: {
    PitchDraw: THREE.MeshStandardMaterial;
  };
};

export default function Stadium(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/in-game/ST.glb",
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[0, 11.163, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stadiump1.geometry}
          material={nodes.Stadiump1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stadiump2.geometry}
          material={nodes.Stadiump2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Barriers.geometry}
          material={nodes.Barriers.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GoalNet.geometry}
          material={nodes.GoalNet.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.PitchBanner.geometry}
          material={nodes.PitchBanner.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Grass_mesh.geometry}
          material={nodes.Grass_mesh.material}
          position={[0, 0.2, 0]}
          scale={[1525.289, 50.843, 2287.934]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pitch_mesh.geometry}
          material={materials.PitchDraw}
          position={[0, 0.2, 0]}
          scale={[1525.289, 50.843, 2287.934]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/in-game/ST.glb");
