/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { Outlines, useGLTF, useTexture } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { JSX, useMemo } from "react";

type GLTFResult = GLTF & {
  nodes: {
    Stadiump1: THREE.Mesh;
    Stadiump2: THREE.Mesh;
    Barriers: THREE.Mesh;
    GoalNet: THREE.Mesh;
    PitchBanner: THREE.Mesh;
    Grass_mesh: THREE.Mesh;
    Pitch_mesh: THREE.Mesh;
  };
  materials: {
    PitchDraw: THREE.MeshStandardMaterial;
  };
};

export default function Stadium(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/in-game/ST.glb",
  ) as unknown as GLTFResult;

  const alphaMap = useTexture("/models/in-game/Pitch desing.png");
  const netTexture = useTexture("/models/in-game/Net.png");

  const pitchMaterial = useMemo(() => {
    const material = new THREE.MeshStandardMaterial();
    material.side = THREE.DoubleSide;
    material.emissive.set("#0088ff");
    material.transparent = true;
    material.alphaMap = alphaMap;
    material.opacity = 0.6;

    return material;
  }, [materials]);

  const netMaterial = useMemo(() => {
    const material = new THREE.MeshStandardMaterial();
    material.side = THREE.DoubleSide;
    material.emissive.set("#ff5a00");
    material.emissiveIntensity = 200;
    material.transparent = true;
    material.alphaMap = netTexture;
    material.opacity = 0.6;
    return material;
  }, [materials]);

  const grassMaterial = useMemo(() => {
    const originalMat = nodes.Grass_mesh.material as THREE.MeshStandardMaterial;
    const mat = originalMat.clone();
    if (mat.map) {
      mat.map = mat.map.clone();
      mat.map.wrapS = THREE.RepeatWrapping;
      mat.map.wrapT = THREE.RepeatWrapping;
      mat.map.colorSpace = THREE.SRGBColorSpace;
      mat.map.repeat.set(8, 8);
      mat.map.offset.set(0, 0);
    }
    // Reduce contrast by lifting shadows with emissive
    return mat;
  }, [nodes.Grass_mesh.material]);

  return (
    <group {...props} dispose={null}>
      <group position={[0, 11.163, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stadiump1.geometry}
          material={nodes.Stadiump1.material}
        >
          <Outlines thickness={0.5} color="black" angle={0} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Stadiump2.geometry}
          material={nodes.Stadiump2.material}
        >
          <Outlines thickness={0.5} color="black" angle={0} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Barriers.geometry}
          material={nodes.Barriers.material}
        >
          <Outlines thickness={0.5} color="black" angle={0} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.GoalNet.geometry}
          material={netMaterial}
        >
          <Outlines thickness={0.5} color="black" angle={0} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.PitchBanner.geometry}
          material={nodes.PitchBanner.material}
        ></mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Grass_mesh.geometry}
          material={grassMaterial}
          position={[0, 0.2, 0]}
          scale={[1525.289, 50.843, 2287.934]}
        ></mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pitch_mesh.geometry}
          material={pitchMaterial}
          position={[0, 0.2, 0]}
          scale={[1525.289, 50.843, 2287.934]}
        ></mesh>
      </group>
    </group>
  );
}

useGLTF.preload("/models/in-game/ST.glb");
