/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { Ref, useEffect, useMemo, useRef } from "react";
import { useGLTF, useAnimations, useTexture } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Beard: THREE.SkinnedMesh;
    Hair_1: THREE.SkinnedMesh;
    Hair_2: THREE.SkinnedMesh;
    Visor_1: THREE.SkinnedMesh;
    Visor_2: THREE.SkinnedMesh;
    Visor_3: THREE.SkinnedMesh;
    Body_2: THREE.SkinnedMesh;
    mixamorigHips: THREE.Bone;
  };
  materials: {
    Accesories_Mat: THREE.MeshStandardMaterial;
  };
  animations: object[];
};

export function ModelBody2(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, animations } = useGLTF(
    "/models/Male/male_body_2.glb"
  ) as GLTFResult;

  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (actions) {
      actions["Break"]?.play();
    }
  }, [actions]);

  const bodyTexture = useTexture(
    "/models/Male/textures/MainBody_Skin2_BaseColor.png"
  );

  const accesoriesTexture = useTexture(
    "/models/Male/textures/Accesories_Mat_BaseColor.png"
  );

  const baseMaterial = useMemo(() => {
    const material = new THREE.MeshBasicMaterial({
      map: bodyTexture,
      color: new THREE.Color(0xffffff),
      vertexColors: false,
    });

    // Ensure proper color space
    if (bodyTexture) {
      bodyTexture.colorSpace = THREE.SRGBColorSpace;
      // bodyTexture.flipY = true; // Common for GLTF textures
    }

    return material;
  }, [bodyTexture]);

  const accesoriesMaterial = useMemo(() => {
    const material = new THREE.MeshBasicMaterial({
      map: accesoriesTexture,
      color: new THREE.Color(0xffffff),
      vertexColors: true,
    });

    // Ensure proper color space
    if (accesoriesTexture) {
      accesoriesTexture.colorSpace = THREE.SRGBColorSpace;
      // accesoriesTexture.flipY = true;
    }

    return material;
  }, [accesoriesTexture]);

  return (
    <group ref={group as Ref<THREE.Group>} {...props} dispose={null}>
      <group name="Scene">
        <group>
          <group name="Body">
            <group name="Customizables_2">
              {/* <skinnedMesh
                name="Beard"
                geometry={nodes.Beard.geometry}
                material={accesoriesMaterial}
                skeleton={nodes.Beard.skeleton}
              /> */}
              <skinnedMesh
                name="Hair_1"
                geometry={nodes.Hair_1.geometry}
                material={accesoriesMaterial}
                skeleton={nodes.Hair_1.skeleton}
              />
              <skinnedMesh
                name="Hair_2"
                geometry={nodes.Hair_2.geometry}
                material={accesoriesMaterial}
                skeleton={nodes.Hair_2.skeleton}
              />
              {/* <skinnedMesh
                name="Visor_1"
                geometry={nodes.Visor_1.geometry}
                material={accesoriesMaterial}
                skeleton={nodes.Visor_1.skeleton}
              /> */}
              <skinnedMesh
                name="Visor_2"
                geometry={nodes.Visor_2.geometry}
                material={accesoriesMaterial}
                skeleton={nodes.Visor_2.skeleton}
              />
              {/* <skinnedMesh
                name="Visor_3"
                geometry={nodes.Visor_3.geometry}
                material={accesoriesMaterial}
                skeleton={nodes.Visor_3.skeleton}
              /> */}
            </group>
            <skinnedMesh
              name="Body_2"
              geometry={nodes.Body_2.geometry}
              material={baseMaterial}
              skeleton={nodes.Body_2.skeleton}
            />
          </group>
          <primitive object={nodes.mixamorigHips} />
          <group name="Character1_Ctrl_Reference">
            <group
              name="Character1_Ctrl_Hips"
              position={[-0.596, 27.483, -2.891]}
            >
              <group
                name="Character1_Ctrl_LeftUpLeg"
                position={[4.175, -2.297, -0.209]}
              >
                <group
                  name="Character1_Ctrl_LeftLeg"
                  position={[2.026, -12.234, -2.076]}
                >
                  <group
                    name="Character1_Ctrl_LeftFoot"
                    position={[0.673, -7.907, -0.406]}
                  >
                    <group
                      name="Character1_Ctrl_LeftToeBase"
                      position={[1.347, -4.25, 4.917]}
                    />
                  </group>
                </group>
              </group>
              <group
                name="Character1_Ctrl_RightUpLeg"
                position={[-4.175, -2.297, -0.095]}
              >
                <group
                  name="Character1_Ctrl_RightLeg"
                  position={[-2.026, -12.234, -2.289]}
                >
                  <group
                    name="Character1_Ctrl_RightFoot"
                    position={[-0.673, -7.907, -0.585]}
                  >
                    <group
                      name="Character1_Ctrl_RightToeBase"
                      position={[-1.347, -4.25, 5.182]}
                    />
                  </group>
                </group>
              </group>
              <group name="Character1_Ctrl_Spine" position={[0, 4.143, -0.477]}>
                <group
                  name="Character1_Ctrl_Spine1"
                  position={[0, 4.833, -0.557]}
                >
                  <group
                    name="Character1_Ctrl_Spine2"
                    position={[0, 5.524, -0.636]}
                  >
                    <group
                      name="Character1_Ctrl_LeftShoulder"
                      position={[3.33, 5.244, -0.711]}
                    >
                      <group
                        name="Character1_Ctrl_LeftArm"
                        position={[6.832, -2.04, 0.01]}
                      >
                        <group
                          name="Character1_Ctrl_LeftForeArm"
                          position={[8.715, -9.464, -0.766]}
                        >
                          <group
                            name="Character1_Ctrl_LeftHand"
                            position={[6.508, -6.159, 1.467]}
                          >
                            <group
                              name="Character1_Ctrl_LeftHandThumb1"
                              position={[-0.558, -1.376, 2.111]}
                            >
                              <group
                                name="Character1_Ctrl_LeftHandThumb2"
                                position={[-0.447, -1.101, 1.689]}
                              >
                                <group
                                  name="Character1_Ctrl_LeftHandThumb3"
                                  position={[-1.265, -1.329, 1.986]}
                                >
                                  <group
                                    name="Character1_Ctrl_LeftHandThumb4"
                                    position={[-0.214, -1.293, 1.657]}
                                  />
                                </group>
                              </group>
                            </group>
                            <group
                              name="Character1_Ctrl_LeftHandIndex1"
                              position={[1.823, -5.085, 3.839]}
                            >
                              <group
                                name="Character1_Ctrl_LeftHandIndex2"
                                position={[0.99, -1.339, 1.041]}
                              >
                                <group
                                  name="Character1_Ctrl_LeftHandIndex3"
                                  position={[1.1, -1.382, 1.12]}
                                >
                                  <group
                                    name="Character1_Ctrl_LeftHandIndex4"
                                    position={[0.701, -0.789, 0.682]}
                                  />
                                </group>
                              </group>
                            </group>
                            <group
                              name="Character1_Ctrl_LeftHandMiddle1"
                              position={[2.75, -5.273, 2.356]}
                            >
                              <group
                                name="Character1_Ctrl_LeftHandMiddle2"
                                position={[1.317, -1.675, 0.69]}
                              >
                                <group
                                  name="Character1_Ctrl_LeftHandMiddle3"
                                  position={[1.33, -1.342, 0.652]}
                                >
                                  <group
                                    name="Character1_Ctrl_LeftHandMiddle4"
                                    position={[1.013, -0.562, 0.439]}
                                  />
                                </group>
                              </group>
                            </group>
                            <group
                              name="Character1_Ctrl_LeftHandRing1"
                              position={[3.555, -5.925, 0.391]}
                            >
                              <group
                                name="Character1_Ctrl_LeftHandRing2"
                                position={[1.268, -1.233, 0.152]}
                              >
                                <group
                                  name="Character1_Ctrl_LeftHandRing3"
                                  position={[1.392, -1.215, 0.175]}
                                >
                                  <group
                                    name="Character1_Ctrl_LeftHandRing4"
                                    position={[1.059, -0.39, 0.166]}
                                  />
                                </group>
                              </group>
                            </group>
                            <group
                              name="Character1_Ctrl_LeftHandPinky1"
                              position={[3.607, -5.793, -1.349]}
                            >
                              <group
                                name="Character1_Ctrl_LeftHandPinky2"
                                position={[1.344, -1.199, -0.249]}
                              >
                                <group
                                  name="Character1_Ctrl_LeftHandPinky3"
                                  position={[1.074, -0.994, -0.206]}
                                >
                                  <group
                                    name="Character1_Ctrl_LeftHandPinky4"
                                    position={[0.649, -0.462, -0.095]}
                                  />
                                </group>
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                    <group
                      name="Character1_Ctrl_RightShoulder"
                      position={[-3.33, 5.244, -0.721]}
                    >
                      <group
                        name="Character1_Ctrl_RightArm"
                        position={[-6.832, -2.04, -0.01]}
                      >
                        <group
                          name="Character1_Ctrl_RightForeArm"
                          position={[-8.715, -9.464, -0.441]}
                        >
                          <group
                            name="Character1_Ctrl_RightHand"
                            position={[-6.508, -6.159, 1.102]}
                          >
                            <group
                              name="Character1_Ctrl_RightHandThumb1"
                              position={[0.688, -1.425, 2.246]}
                            >
                              <group
                                name="Character1_Ctrl_RightHandThumb2"
                                position={[0.55, -1.14, 1.797]}
                              >
                                <group
                                  name="Character1_Ctrl_RightHandThumb3"
                                  position={[1.04, -1.415, 1.983]}
                                >
                                  <group
                                    name="Character1_Ctrl_RightHandThumb4"
                                    position={[0.8, -1.097, 1.465]}
                                  />
                                </group>
                              </group>
                            </group>
                            <group
                              name="Character1_Ctrl_RightHandIndex1"
                              position={[-1.932, -5.114, 3.987]}
                            >
                              <group
                                name="Character1_Ctrl_RightHandIndex2"
                                position={[-1.086, -1.447, 1.127]}
                              >
                                <group
                                  name="Character1_Ctrl_RightHandIndex3"
                                  position={[-1.074, -1.302, 1.07]}
                                >
                                  <group
                                    name="Character1_Ctrl_RightHandIndex4"
                                    position={[-0.545, -0.844, 0.596]}
                                  />
                                </group>
                              </group>
                            </group>
                            <group
                              name="Character1_Ctrl_RightHandMiddle1"
                              position={[-2.841, -5.414, 2.614]}
                            >
                              <group
                                name="Character1_Ctrl_RightHandMiddle2"
                                position={[-1.394, -1.579, 0.415]}
                              >
                                <group
                                  name="Character1_Ctrl_RightHandMiddle3"
                                  position={[-1.394, -1.342, 0.408]}
                                >
                                  <group
                                    name="Character1_Ctrl_RightHandMiddle4"
                                    position={[-1.042, -0.606, 0.293]}
                                  />
                                </group>
                              </group>
                            </group>
                            <group
                              name="Character1_Ctrl_RightHandRing1"
                              position={[-3.877, -6.147, 0.4]}
                            >
                              <group
                                name="Character1_Ctrl_RightHandRing2"
                                position={[-1.26, -1.15, 0.173]}
                              >
                                <group
                                  name="Character1_Ctrl_RightHandRing3"
                                  position={[-1.245, -1.153, 0.17]}
                                >
                                  <group
                                    name="Character1_Ctrl_RightHandRing4"
                                    position={[-0.898, -0.563, 0.134]}
                                  />
                                </group>
                              </group>
                            </group>
                            <group
                              name="Character1_Ctrl_RightHandPinky1"
                              position={[-4.006, -6.264, -1.23]}
                            >
                              <group
                                name="Character1_Ctrl_RightHandPinky2"
                                position={[-1.094, -0.829, -0.205]}
                              >
                                <group
                                  name="Character1_Ctrl_RightHandPinky3"
                                  position={[-1.043, -0.908, -0.219]}
                                >
                                  <group
                                    name="Character1_Ctrl_RightHandPinky4"
                                    position={[-0.603, -0.493, -0.119]}
                                  />
                                </group>
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                    <group
                      name="Character1_Ctrl_Neck"
                      position={[0, 6.214, -0.716]}
                    >
                      <group
                        name="Character1_Ctrl_Head"
                        position={[0, 1.34, 0.449]}
                      />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/Male/male_body_2.glb");
