/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { Ref, useEffect, useMemo, useRef } from "react";
import { useGLTF, useAnimations, useTexture } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Body_3: THREE.SkinnedMesh;
    Beard: THREE.SkinnedMesh;
    Hair_1: THREE.SkinnedMesh;
    Hair_2: THREE.SkinnedMesh;
    Visor_1: THREE.SkinnedMesh;
    Visor_2: THREE.SkinnedMesh;
    Visor_3: THREE.SkinnedMesh;
    mixamorigHips: THREE.Bone;
  };
  materials: {
    MainBody_Mat: THREE.MeshStandardMaterial;
    Accesories_Mat: THREE.MeshStandardMaterial;
  };
};

export function ModelBody3(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, animations } = useGLTF(
    "/models/Male/male_body_3.glb"
  ) as GLTFResult;
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (actions) {
      actions["Break"]?.play();
    }
  }, [actions]);

  const bodyTexture = useTexture(
    "/models/Male/textures/MainBody_Skin3_BaseColor.png"
  );
  const accesoriesTexture = useTexture(
    "/models/Male/textures/Accesories_Mat_BaseColor.png"
  );

  const maskMainBodyTexture = useTexture(
    "/models/Male/textures/Mask_MainBody_Mat_BaseColor.png"
  );

  const baseMaterial = useMemo(() => {
    const material = new THREE.MeshBasicMaterial({
      map: bodyTexture,
      color: new THREE.Color(0xffffff),
      vertexColors: false,
      alphaMap: maskMainBodyTexture,
    //   transparent: true,
    });

    // Ensure proper color space
    if (bodyTexture) {
      bodyTexture.colorSpace = THREE.SRGBColorSpace;
      // bodyTexture.flipY = true; // Common for GLTF textures
    }

    return material;
  }, [bodyTexture]);

  const accesoriesMaterial = useMemo(() => {
    const material = new THREE.MeshBasicMaterial({
      map: accesoriesTexture,
      color: new THREE.Color(0x00ff00),
      vertexColors: true,
    });

    // Ensure proper color space
    if (accesoriesTexture) {
      accesoriesTexture.colorSpace = THREE.SRGBColorSpace;
      // accesoriesTexture.flipY = true;
    }

    return material;
  }, [accesoriesTexture]);

  return (
    <group ref={group as Ref<THREE.Group>} {...props} dispose={null}>
      <group name="Scene">
        <group>
          <group name="Body">
            <skinnedMesh
              name="Body_3"
              geometry={nodes.Body_3.geometry}
              material={baseMaterial}
              skeleton={nodes.Body_3.skeleton}
            />
            <group name="Customizables_3">
              {/* <skinnedMesh
                name="Beard"
                geometry={nodes.Beard.geometry}
                material={accesoriesMaterial}
                skeleton={nodes.Beard.skeleton}
              /> */}
              {/* <skinnedMesh
                name="Hair_1"
                geometry={nodes.Hair_1.geometry}
                material={accesoriesMaterial}
                skeleton={nodes.Hair_1.skeleton}
              /> */}
              {/* <skinnedMesh
                name="Hair_2"
                geometry={nodes.Hair_2.geometry}
                material={accesoriesMaterial}
                skeleton={nodes.Hair_2.skeleton}
              /> */}
              {/* <skinnedMesh
                name="Visor_1"
                geometry={nodes.Visor_1.geometry}
                material={accesoriesMaterial}
                skeleton={nodes.Visor_1.skeleton}
              /> */}
              {/* <skinnedMesh
                name="Visor_2"
                geometry={nodes.Visor_2.geometry}
                material={accesoriesMaterial}
                skeleton={nodes.Visor_2.skeleton}
              /> */}
              <skinnedMesh
                name="Visor_3"
                geometry={nodes.Visor_3.geometry}
                material={accesoriesMaterial}
                skeleton={nodes.Visor_3.skeleton}
              />
            </group>
          </group>
          <primitive object={nodes.mixamorigHips} />
          <group name="Character1_Ctrl_Reference">
            <group name="Character1_Ctrl_Hips" position={[0, 24.37, 0.34]}>
              <group
                name="Character1_Ctrl_LeftUpLeg"
                position={[4.11, -1.98, -0.4]}
              >
                <group
                  name="Character1_Ctrl_LeftLeg"
                  position={[0.18, -10.55, 0.28]}
                >
                  <group
                    name="Character1_Ctrl_LeftFoot"
                    position={[-0.18, -5.59, -0.85]}
                  >
                    <group
                      name="Character1_Ctrl_LeftToeBase"
                      position={[1.55, -5.43, 5.63]}
                    />
                  </group>
                </group>
              </group>
              <group
                name="Character1_Ctrl_RightUpLeg"
                position={[-4.11, -1.98, -0.31]}
              >
                <group
                  name="Character1_Ctrl_RightLeg"
                  position={[-0.18, -10.56, 0.15]}
                >
                  <group
                    name="Character1_Ctrl_RightFoot"
                    position={[0.18, -5.57, -0.82]}
                  >
                    <group
                      name="Character1_Ctrl_RightToeBase"
                      position={[-1.55, -5.43, 5.01]}
                    />
                  </group>
                </group>
              </group>
              <group name="Character1_Ctrl_Spine" position={[0, 3.57, -0.48]}>
                <group
                  name="Character1_Ctrl_Spine1"
                  position={[0, 4.17, -0.56]}
                >
                  <group
                    name="Character1_Ctrl_Spine2"
                    position={[0, 4.76, -0.64]}
                  >
                    <group
                      name="Character1_Ctrl_LeftShoulder"
                      position={[3.23, 4.79, -0.73]}
                    >
                      <group
                        name="Character1_Ctrl_LeftArm"
                        position={[6.55, -0.15, 0]}
                      >
                        <group
                          name="Character1_Ctrl_LeftForeArm"
                          position={[11.53, -0.17, 0.96]}
                        >
                          <group
                            name="Character1_Ctrl_LeftHand"
                            position={[7.18, -0.11, 0.6]}
                          >
                            <group
                              name="Character1_Ctrl_LeftHandThumb1"
                              position={[1.32, -0.43, 1.79]}
                            >
                              <group
                                name="Character1_Ctrl_LeftHandThumb2"
                                position={[1.31, -0.66, 1.06]}
                              >
                                <group
                                  name="Character1_Ctrl_LeftHandThumb3"
                                  position={[1.65, -0.83, 1.33]}
                                >
                                  <group
                                    name="Character1_Ctrl_LeftHandThumb4"
                                    position={[1.04, -0.53, 0.85]}
                                  />
                                </group>
                              </group>
                            </group>
                            <group
                              name="Character1_Ctrl_LeftHandIndex1"
                              position={[5.21, -0.08, 1.82]}
                            >
                              <group
                                name="Character1_Ctrl_LeftHandIndex2"
                                position={[1.73, -0.03, 0.14]}
                              >
                                <group
                                  name="Character1_Ctrl_LeftHandIndex3"
                                  position={[1.75, -0.03, 0.14]}
                                >
                                  <group
                                    name="Character1_Ctrl_LeftHandIndex4"
                                    position={[1.15, -0.02, 0.1]}
                                  />
                                </group>
                              </group>
                            </group>
                            <group
                              name="Character1_Ctrl_LeftHandMiddle1"
                              position={[5.63, -0.09, 0.47]}
                            >
                              <group
                                name="Character1_Ctrl_LeftHandMiddle2"
                                position={[1.77, -0.03, 0.15]}
                              >
                                <group
                                  name="Character1_Ctrl_LeftHandMiddle3"
                                  position={[1.64, -0.02, 0.14]}
                                >
                                  <group
                                    name="Character1_Ctrl_LeftHandMiddle4"
                                    position={[1.04, -0.02, 0.09]}
                                  />
                                </group>
                              </group>
                            </group>
                            <group
                              name="Character1_Ctrl_LeftHandRing1"
                              position={[5.82, -0.5, -1.49]}
                            >
                              <group
                                name="Character1_Ctrl_LeftHandRing2"
                                position={[1.55, -0.02, 0.13]}
                              >
                                <group
                                  name="Character1_Ctrl_LeftHandRing3"
                                  position={[1.47, -0.02, 0.13]}
                                >
                                  <group
                                    name="Character1_Ctrl_LeftHandRing4"
                                    position={[0.94, -0.01, 0.08]}
                                  />
                                </group>
                              </group>
                            </group>
                            <group
                              name="Character1_Ctrl_LeftHandPinky1"
                              position={[5.28, -0.9, -2.43]}
                            >
                              <group
                                name="Character1_Ctrl_LeftHandPinky2"
                                position={[1.3, -0.02, 0.1]}
                              >
                                <group
                                  name="Character1_Ctrl_LeftHandPinky3"
                                  position={[1.46, -0.02, 0.12]}
                                >
                                  <group
                                    name="Character1_Ctrl_LeftHandPinky4"
                                    position={[0.96, -0.01, 0.08]}
                                  />
                                </group>
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                    <group
                      name="Character1_Ctrl_RightShoulder"
                      position={[-3.23, 4.79, -0.73]}
                    >
                      <group
                        name="Character1_Ctrl_RightArm"
                        position={[-6.55, -0.15, 0]}
                      >
                        <group
                          name="Character1_Ctrl_RightForeArm"
                          position={[-11.57, -0.02, 0.12]}
                        >
                          <group
                            name="Character1_Ctrl_RightHand"
                            position={[-7.21, -0.01, 0.07]}
                          >
                            <group
                              name="Character1_Ctrl_RightHandThumb1"
                              position={[-1.4, -0.68, 1.55]}
                            >
                              <group
                                name="Character1_Ctrl_RightHandThumb2"
                                position={[-1.35, -0.79, 0.8]}
                              >
                                <group
                                  name="Character1_Ctrl_RightHandThumb3"
                                  position={[-1.72, -1, 1.02]}
                                >
                                  <group
                                    name="Character1_Ctrl_RightHandThumb4"
                                    position={[-1.26, -0.74, 0.75]}
                                  />
                                </group>
                              </group>
                            </group>
                            <group
                              name="Character1_Ctrl_RightHandIndex1"
                              position={[-5.42, -0.13, 1.44]}
                            >
                              <group
                                name="Character1_Ctrl_RightHandIndex2"
                                position={[-1.85, 0, 0.02]}
                              >
                                <group
                                  name="Character1_Ctrl_RightHandIndex3"
                                  position={[-1.68, 0, 0.02]}
                                >
                                  <group
                                    name="Character1_Ctrl_RightHandIndex4"
                                    position={[-1.06, 0, 0.01]}
                                  />
                                </group>
                              </group>
                            </group>
                            <group
                              name="Character1_Ctrl_RightHandMiddle1"
                              position={[-5.56, -0.01, 0.06]}
                            >
                              <group
                                name="Character1_Ctrl_RightHandMiddle2"
                                position={[-1.75, 0, 0.02]}
                              >
                                <group
                                  name="Character1_Ctrl_RightHandMiddle3"
                                  position={[-1.71, 0, 0.02]}
                                >
                                  <group
                                    name="Character1_Ctrl_RightHandMiddle4"
                                    position={[-1.09, 0, 0.01]}
                                  />
                                </group>
                              </group>
                            </group>
                            <group
                              name="Character1_Ctrl_RightHandRing1"
                              position={[-5.86, 0.11, -2.03]}
                            >
                              <group
                                name="Character1_Ctrl_RightHandRing2"
                                position={[-1.45, 0, 0.02]}
                              >
                                <group
                                  name="Character1_Ctrl_RightHandRing3"
                                  position={[-1.48, 0, 0.02]}
                                >
                                  <group
                                    name="Character1_Ctrl_RightHandRing4"
                                    position={[-0.96, 0, 0.01]}
                                  />
                                </group>
                              </group>
                            </group>
                            <group
                              name="Character1_Ctrl_RightHandPinky1"
                              position={[-5.48, -0.19, -3.28]}
                            >
                              <group
                                name="Character1_Ctrl_RightHandPinky2"
                                position={[-1.34, 0, 0.01]}
                              >
                                <group
                                  name="Character1_Ctrl_RightHandPinky3"
                                  position={[-1.19, 0, 0.01]}
                                >
                                  <group
                                    name="Character1_Ctrl_RightHandPinky4"
                                    position={[-0.67, 0, 0.01]}
                                  />
                                </group>
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                    <group
                      name="Character1_Ctrl_Neck"
                      position={[0, 5.36, -0.73]}
                    >
                      <group
                        name="Character1_Ctrl_Head"
                        position={[0, 2.64, 0.9]}
                      />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/Male/male_body_3.glb");
