/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { useEffect, useMemo, useRef } from "react";
import { useGLTF, useAnimations, useTexture } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useCharacterShader } from "../webgl/components/character-models/programs/useCharacterShader";

type GLTFResult = GLTF & {
  nodes: {
    Beard: THREE.SkinnedMesh;
    Hair_1: THREE.SkinnedMesh;
    Hair_2: THREE.SkinnedMesh;
    Visor_1: THREE.SkinnedMesh;
    Visor_2: THREE.SkinnedMesh;
    Visor_3: THREE.SkinnedMesh;
    Body_1: THREE.SkinnedMesh;
    mixamorigHips: THREE.Bone;
  };
  materials: {
    Accesories_Mat: THREE.MeshStandardMaterial;
    MainBody_Mat: THREE.MeshStandardMaterial;
  };
};

export function MaleBody1(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>(null);
  const { nodes, animations } = useGLTF(
    "/models/Male/male_last_2.glb",
  ) as GLTFResult;
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (actions) {
      actions["Break"]?.play();
    }
  }, [actions]);

  const bodyTexture = useTexture(
    "/models/Male/textures/MainBody_Skin1_BaseColor.png",
  );
  const accesoriesTexture = useTexture(
    "/models/Male/textures/Accesories_Mat_BaseColor.png",
  );

  const characterShader = useCharacterShader({ baseTexture: bodyTexture });

  const baseMaterial = useMemo(() => {
    const material = new THREE.MeshBasicMaterial({
      map: bodyTexture,
      color: new THREE.Color(0xffffff),
      vertexColors: false,
    });

    // Ensure proper color space
    if (bodyTexture) {
      bodyTexture.colorSpace = THREE.SRGBColorSpace;
      // bodyTexture.flipY = true; // Common for GLTF textures
    }

    return material;
  }, [bodyTexture]);

  const accesoriesMaterial = useMemo(() => {
    const material = new THREE.MeshBasicMaterial({
      map: accesoriesTexture,
      color: new THREE.Color(0x1ff4f10),
      vertexColors: true,
    });

    // Ensure proper color space
    if (accesoriesTexture) {
      accesoriesTexture.colorSpace = THREE.SRGBColorSpace;
      // accesoriesTexture.flipY = true;
    }

    return material;
  }, [accesoriesTexture]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="AmbientLight" />
        <group name="scene_(3)glb">
          <group name="AmbientLight_1" />
          <group>
            <group name="Body">
              <group name="Customizables_1">
                <skinnedMesh
                  name="Beard"
                  geometry={nodes.Beard.geometry}
                  material={accesoriesMaterial}
                  skeleton={nodes.Beard.skeleton}
                />
                <skinnedMesh
                  name="Hair_1"
                  geometry={nodes.Hair_1.geometry}
                  material={accesoriesMaterial}
                  skeleton={nodes.Hair_1.skeleton}
                />
                {/* <skinnedMesh
                  name="Hair_2"
                  geometry={nodes.Hair_2.geometry}
                  material={accesoriesMaterial}
                  skeleton={nodes.Hair_2.skeleton}
                /> */}
                <skinnedMesh
                  name="Visor_1"
                  geometry={nodes.Visor_1.geometry}
                  material={accesoriesMaterial}
                  skeleton={nodes.Visor_1.skeleton}
                />
                {/* <skinnedMesh
                  name="Visor_2"
                  geometry={nodes.Visor_2.geometry}
                  material={accesoriesMaterial}
                  skeleton={nodes.Visor_2.skeleton}
                /> */}
                {/* <skinnedMesh
                  name="Visor_3"
                  geometry={nodes.Visor_3.geometry}
                  material={accesoriesMaterial}
                  skeleton={nodes.Visor_3.skeleton}
                /> */}
              </group>
              <skinnedMesh
                name="Body_1"
                geometry={nodes.Body_1.geometry}
                material={baseMaterial}
                skeleton={nodes.Body_1.skeleton}
              />
            </group>
            <primitive object={nodes.mixamorigHips} />
            <group name="Character1_Ctrl_Reference">
              <group
                name="Character1_Ctrl_Hips"
                position={[0.009, 26.96, -0.105]}
              >
                <group
                  name="Character1_Ctrl_LeftUpLeg"
                  position={[4.172, -2.096, 0.047]}
                >
                  <group
                    name="Character1_Ctrl_LeftLeg"
                    position={[0.477, -12.196, 0.645]}
                  >
                    <group
                      name="Character1_Ctrl_LeftFoot"
                      position={[-0.478, -7.826, -1.336]}
                    >
                      <group
                        name="Character1_Ctrl_LeftToeBase"
                        position={[1.263, -3.98, 5.005]}
                      />
                    </group>
                  </group>
                </group>
                <group
                  name="Character1_Ctrl_RightUpLeg"
                  position={[-4.189, -2.062, 0.044]}
                >
                  <group
                    name="Character1_Ctrl_RightLeg"
                    position={[-0.484, -12.193, 0.539]}
                  >
                    <group
                      name="Character1_Ctrl_RightFoot"
                      position={[0.483, -7.859, -1.219]}
                    >
                      <group
                        name="Character1_Ctrl_RightToeBase"
                        position={[-1.263, -3.982, 5.087]}
                      />
                    </group>
                  </group>
                </group>
                <group
                  name="Character1_Ctrl_Spine"
                  position={[0.015, 3.749, -0.417]}
                >
                  <group
                    name="Character1_Ctrl_Spine1"
                    position={[0, 4.374, -0.486]}
                  >
                    <group
                      name="Character1_Ctrl_Spine2"
                      position={[0, 4.999, -0.556]}
                    >
                      <group
                        name="Character1_Ctrl_LeftShoulder"
                        position={[3.136, 4.94, -0.591]}
                      >
                        <group
                          name="Character1_Ctrl_LeftArm"
                          position={[6.487, -0.374, 0.068]}
                        >
                          <group
                            name="Character1_Ctrl_LeftForeArm"
                            position={[12.528, 0.001, 0]}
                          >
                            <group
                              name="Character1_Ctrl_LeftHand"
                              position={[10.585, 0, 0]}
                            >
                              <group
                                name="Character1_Ctrl_LeftHandThumb1"
                                position={[1.071, -0.753, 2.005]}
                              >
                                <group
                                  name="Character1_Ctrl_LeftHandThumb2"
                                  position={[1.484, -0.856, 0.856]}
                                >
                                  <group
                                    name="Character1_Ctrl_LeftHandThumb3"
                                    position={[1.98, -1.143, 1.142]}
                                  >
                                    <group
                                      name="Character1_Ctrl_LeftHandThumb4"
                                      position={[1.445, -0.834, 0.835]}
                                    />
                                  </group>
                                </group>
                              </group>
                              <group
                                name="Character1_Ctrl_LeftHandIndex1"
                                position={[4.987, -0.265, 1.643]}
                              >
                                <group
                                  name="Character1_Ctrl_LeftHandIndex2"
                                  position={[2.034, 0, -0.002]}
                                >
                                  <group
                                    name="Character1_Ctrl_LeftHandIndex3"
                                    position={[2.142, 0, 0.004]}
                                  >
                                    <group
                                      name="Character1_Ctrl_LeftHandIndex4"
                                      position={[1.403, 0, -0.002]}
                                    />
                                  </group>
                                </group>
                              </group>
                              <group
                                name="Character1_Ctrl_LeftHandMiddle1"
                                position={[5.632, 0.005, 0.005]}
                              >
                                <group
                                  name="Character1_Ctrl_LeftHandMiddle2"
                                  position={[1.89, 0, 0.002]}
                                >
                                  <group
                                    name="Character1_Ctrl_LeftHandMiddle3"
                                    position={[1.918, 0, 0.001]}
                                  >
                                    <group
                                      name="Character1_Ctrl_LeftHandMiddle4"
                                      position={[1.209, 0, -0.004]}
                                    />
                                  </group>
                                </group>
                              </group>
                              <group
                                name="Character1_Ctrl_LeftHandRing1"
                                position={[5.226, -0.087, -2.255]}
                              >
                                <group
                                  name="Character1_Ctrl_LeftHandRing2"
                                  position={[1.668, 0, 0.001]}
                                >
                                  <group
                                    name="Character1_Ctrl_LeftHandRing3"
                                    position={[1.88, 0, 0.003]}
                                  >
                                    <group
                                      name="Character1_Ctrl_LeftHandRing4"
                                      position={[1.266, 0, -0.004]}
                                    />
                                  </group>
                                </group>
                              </group>
                              <group
                                name="Character1_Ctrl_LeftHandPinky1"
                                position={[4.417, -0.233, -3.748]}
                              >
                                <group
                                  name="Character1_Ctrl_LeftHandPinky2"
                                  position={[1.922, 0, -0.004]}
                                >
                                  <group
                                    name="Character1_Ctrl_LeftHandPinky3"
                                    position={[1.447, 0, -0.004]}
                                  >
                                    <group
                                      name="Character1_Ctrl_LeftHandPinky4"
                                      position={[0.794, 0, -0.001]}
                                    />
                                  </group>
                                </group>
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                      <group
                        name="Character1_Ctrl_RightShoulder"
                        position={[-3.136, 4.94, -0.659]}
                      >
                        <group
                          name="Character1_Ctrl_RightArm"
                          position={[-6.486, -0.377, -0.068]}
                        >
                          <group
                            name="Character1_Ctrl_RightForeArm"
                            position={[-12.519, 0, 0]}
                          >
                            <group
                              name="Character1_Ctrl_RightHand"
                              position={[-10.603, 0, 0]}
                            >
                              <group
                                name="Character1_Ctrl_RightHandThumb1"
                                position={[-1.001, -0.656, 1.825]}
                              >
                                <group
                                  name="Character1_Ctrl_RightHandThumb2"
                                  position={[-1.35, -0.782, 0.784]}
                                >
                                  <group
                                    name="Character1_Ctrl_RightHandThumb3"
                                    position={[-2.025, -1.169, 1.17]}
                                  >
                                    <group
                                      name="Character1_Ctrl_RightHandThumb4"
                                      position={[-1.529, -0.885, 0.889]}
                                    />
                                  </group>
                                </group>
                              </group>
                              <group
                                name="Character1_Ctrl_RightHandIndex1"
                                position={[-5.19, -0.204, 1.779]}
                              >
                                <group
                                  name="Character1_Ctrl_RightHandIndex2"
                                  position={[-2.007, 0, -0.002]}
                                >
                                  <group
                                    name="Character1_Ctrl_RightHandIndex3"
                                    position={[-2.005, 0, 0.003]}
                                  >
                                    <group
                                      name="Character1_Ctrl_RightHandIndex4"
                                      position={[-1.125, 0, -0.001]}
                                    />
                                  </group>
                                </group>
                              </group>
                              <group
                                name="Character1_Ctrl_RightHandMiddle1"
                                position={[-5.355, 0.001, 0.003]}
                              >
                                <group
                                  name="Character1_Ctrl_RightHandMiddle2"
                                  position={[-2.09, 0, 0.001]}
                                >
                                  <group
                                    name="Character1_Ctrl_RightHandMiddle3"
                                    position={[-1.883, 0, 0]}
                                  >
                                    <group
                                      name="Character1_Ctrl_RightHandMiddle4"
                                      position={[-1.118, 0, -0.001]}
                                    />
                                  </group>
                                </group>
                              </group>
                              <group
                                name="Character1_Ctrl_RightHandRing1"
                                position={[-5.107, 0.163, -2.183]}
                              >
                                <group
                                  name="Character1_Ctrl_RightHandRing2"
                                  position={[-1.883, 0, -0.003]}
                                >
                                  <group
                                    name="Character1_Ctrl_RightHandRing3"
                                    position={[-1.859, 0, -0.003]}
                                  >
                                    <group
                                      name="Character1_Ctrl_RightHandRing4"
                                      position={[-1.245, 0, -0.004]}
                                    />
                                  </group>
                                </group>
                              </group>
                              <group
                                name="Character1_Ctrl_RightHandPinky1"
                                position={[-4.663, -0.277, -3.663]}
                              >
                                <group
                                  name="Character1_Ctrl_RightHandPinky2"
                                  position={[-1.629, 0, 0.001]}
                                >
                                  <group
                                    name="Character1_Ctrl_RightHandPinky3"
                                    position={[-1.546, 0, 0.003]}
                                  >
                                    <group
                                      name="Character1_Ctrl_RightHandPinky4"
                                      position={[-0.853, 0, -0.004]}
                                    />
                                  </group>
                                </group>
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                      <group
                        name="Character1_Ctrl_Neck"
                        position={[0, 5.624, -0.625]}
                      >
                        <group
                          name="Character1_Ctrl_Head"
                          position={[0, 0.591, 0.196]}
                        />
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/Male/male_last_2.glb");
