/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 character-2.glb --types 
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type ActionName = 'animation_0'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    mesh_0: THREE.Mesh
    mesh_1: THREE.Mesh
    mesh_2: THREE.Mesh
    mesh_3: THREE.Mesh
    mesh_4: THREE.Mesh
    mesh_5: THREE.Mesh
    mesh_6: THREE.Mesh
  };
  materials: object;
  animations: GLTFAction[];
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const ref = useRef<THREE.Group>(null)
  const model  = useGLTF('/models/character-2.glb') as GLTFResult
  const { nodes, animations } = model
  const { actions } = useAnimations(animations, ref)

  // useEffect(() => {
  //   const anim = actions['animation_0']
  //   console.log(anim)
  //   anim?.play()
  // }, [])


  return (
    <group  ref={ref} {...props} dispose={null}>
      <group name="defaultScene">
        <group>
          <group>
            <group>
              <mesh name="mesh_0" geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
              <mesh name="mesh_1" geometry={nodes.mesh_1.geometry} material={nodes.mesh_1.material} />
              <mesh name="mesh_2" geometry={nodes.mesh_2.geometry} material={nodes.mesh_2.material} />
              <mesh name="mesh_3" geometry={nodes.mesh_3.geometry} material={nodes.mesh_3.material} />
              <mesh name="mesh_4" geometry={nodes.mesh_4.geometry} material={nodes.mesh_4.material} />
              <mesh name="mesh_5" geometry={nodes.mesh_5.geometry} material={nodes.mesh_5.material} />
            </group>
            <mesh name="mesh_6" geometry={nodes.mesh_6.geometry} material={nodes.mesh_6.material} />
          </group>
        </group>
        <group position={[0.009, 26.627, 0.025]} rotation={[-0.027, -0.002, -0.019]} scale={100} />
        <group />
      </group>
    </group>
  )
}

useGLTF.preload('/models/character-2.glb')
