/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 character-1.glb --types 
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Beard: THREE.Mesh;
    Hair_1: THREE.Mesh;
    Hair_2: THREE.Mesh;
    Visor_1: THREE.Mesh;
    Visor_2: THREE.Mesh;
    Visor_3: THREE.Mesh;
    Low_2: THREE.Mesh;
  };
  materials: {
    Accesories_Mat: THREE.MeshStandardMaterial;
    MainBody_Mat: THREE.MeshStandardMaterial;
  };
  animations: object[];
};

export function CharacterModel(props: JSX.IntrinsicElements["group"]) {
  const {nodes, materials} = useGLTF("/models/character-1.glb") as GLTFResult;
  
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-0.638, 57.304, -2.058]}>
          <group position={[0.638, -57.304, 2.058]}>
            <group position={[-0.638, 57.304, -2.058]}>
              <group position={[0.638, -57.304, 2.058]}>
                <group position={[-0.638, 36.183, 109.371]}>
                  <group position={[0.638, -36.183, -109.371]}>
                    <group position={[-0.638, 36.183, 109.371]}>
                      <mesh
                        geometry={nodes.Beard.geometry}
                        material={materials.Accesories_Mat}
                        position={[0.638, -36.183, -109.371]}
                      />
                    </group>
                  </group>
                </group>
                <group position={[-0.638, 36.183, 109.371]}>
                  <group position={[0.638, -36.183, -109.371]}>
                    <group position={[-0.638, 36.183, 109.371]}>
                      <mesh
                        geometry={nodes.Hair_1.geometry}
                        material={materials.Accesories_Mat}
                        position={[0.638, -36.183, -109.371]}
                      />
                    </group>
                  </group>
                </group>
                <group position={[-0.779, 60.568, -2.058]}>
                  <group position={[0.779, -60.568, 2.058]}>
                    <group position={[-0.779, 60.568, -2.058]}>
                      <mesh
                        geometry={nodes.Hair_2.geometry}
                        material={materials.Accesories_Mat}
                        position={[0.779, -60.568, 2.058]}
                      />
                    </group>
                  </group>
                </group>
                <group position={[-0.638, 36.183, 109.371]}>
                  <group position={[0.638, -36.183, -109.371]}>
                    <group position={[-0.638, 36.183, 109.371]}>
                      <mesh
                        geometry={nodes.Visor_1.geometry}
                        material={materials.Accesories_Mat}
                        position={[0.638, -36.183, -109.371]}
                      />
                    </group>
                  </group>
                </group>
                <group position={[-0.638, 36.183, 109.371]}>
                  <group position={[0.638, -36.183, -109.371]}>
                    <group position={[-0.638, 36.183, 109.371]}>
                      <mesh
                        geometry={nodes.Visor_2.geometry}
                        material={materials.Accesories_Mat}
                        position={[0.638, -36.183, -109.371]}
                      />
                    </group>
                  </group>
                </group>
                <group position={[-0.638, 36.183, 109.371]}>
                  <group position={[0.638, -36.183, -109.371]}>
                    <group position={[-0.638, 36.183, 109.371]}>
                      <mesh
                        geometry={nodes.Visor_3.geometry}
                        material={materials.Accesories_Mat}
                        position={[0.638, -36.183, -109.371]}
                      />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
        <group position={[-0.666, 32.45, -2.16]}>
          <group position={[0.666, -32.45, 2.16]}>
            <group position={[-0.666, 32.45, -2.16]}>
              <mesh
                geometry={nodes.Low_2.geometry}
                material={materials.MainBody_Mat}
                position={[0.666, -32.45, 2.16]}
              />
            </group>
          </group>
        </group>
      </group>

    </group>
  );
}

useGLTF.preload("/models/character-1.glb");
